#!/usr/bin/env bash

function _load_wf_msg_deps {
	_wf_msg_path=$(dirname "$(readlink -f "$(which wf-msg)")")
	# shellcheck disable=1091
	source "$_wf_msg_path/_bash_args_parser.bash"
	# shellcheck disable=1091
	source "$_wf_msg_path/_lib.bash"
	# shellcheck disable=1091
	source "$_wf_msg_path/_help.bash"
}

trap "exit 1" TERM
export _TOP_PID=$$
_load_wf_msg_deps

_init "$@"
